FROM rocker/shiny-verse:4

RUN install2.r --error \
    --deps FALSE \
    data.table \
    RColorBrewer \
    httr \
    shinydashboard \
    tidyjson \
    jsonlite \
    htmlwidgets \
    DT \
    crosstalk \
    plotly
