#!/bin/sh

date=$(date '+%Y-%m-%dT%T')
echo "Running mhira backups prune... ${date}"

# Deletes all backups older than 30 days, except for the first of every month
# Refer to https://superuser.com/a/1601525
find /backups/ ! -name '*01.tar.gz' -mtime +30 -exec rm {} \;

echo "Finished running mhira backups prune... ${date}"