#!/bin/sh

date=$(date '+%Y-%m-%dT%T')
echo "Running mhira backups prune... ${date}"

# Deletes all backups older than 30 days
# Refer to https://superuser.com/a/1601525
find /backups/postgres/ -mtime +30 -exec rm {} \;
find /backups/mongo/ -mtime +30 -exec rm {} \;

echo "Finished running mhira backups prune... ${date}"