#!/bin/sh

echo "Running mhira data restore..."

get_archive() {
    i=1
    selected_archive=""
    for archive in $1; do
        if [ $i -eq $2 ]; then
            selected_archive=$archive
            break
        fi
        i=$((i+1))
    done

    echo "$selected_archive"
}

restore() {
    archives=$2
    valid_selection=false

    i=1
    for archive in $archives; do
        echo "$i) $archive"
        i=$((i+1))
    done

    while true; do
        read -p "Enter the index of the $1 archive you want to restore: " selected_index

        selected_archive=$(get_archive "$archives" "$selected_index")

        if [ -z "$selected_archive" ]; then
            echo "Invalid selection."
        else
            break
        fi
    done

    if [ "$1" == "PostgreSQL" ]; then
        psql -h mhira-docker-postgres-1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" -f "$selected_archive"
    elif [ "$1" == "MongoDB" ]; then
        mongorestore --host mhira-docker-mongo-1 --archive="$selected_archive"
    fi

    echo "Finished running mhira $1 data restore!"
}

restore "PostgreSQL" "/backups/postgres/*"

restore "MongoDB" "/backups/mongo/*"